<?php

namespace Lys\Until\Test;

use Lys\Until\Img\ImgQuality;

use PHPUnit\Framework\TestCase;

$file_load_path = __DIR__.'/../../../autoload.php';
if (file_exists($file_load_path)) {
    include $file_load_path;
} else {
    $vendor = __DIR__.'/../vendor/autoload.php';
    include $vendor;
}


/**
 * @method assertEquals($a, $b)
 */
class ImgTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        ini_set('date.timezone', 'Asia/Shanghai');
    }

    /**
     * php vendor/bin/phpunit tests/DemoTest.php --filter testResize
     * @throws
     */
    public function testResize()
    {
        $quality = new ImgQuality('./5.39M.png','./'.uniqid(date('YmdHis')).'.jpg');
        $res = $quality->toJpg(90,1024*1024);
        var_dump($res,$quality->getErrorMsg());
    }



}
